# Generated by Django 3.2.13 on 2022-05-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.TextField()),
                ('categoryName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('userName', models.CharField(max_length=200)),
                ('passWord', models.CharField(max_length=200)),
                ('avatar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('createAt', models.CharField(max_length=100)),
                ('mainImg', models.TextField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyId', models.TextField()),
                ('content', models.TextField()),
                ('imageBody', models.TextField()),
                ('tittleBody', models.TextField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
    ]
