# Generated by Django 3.2.13 on 2022-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.TextField(default='790e890d571753148bbc9c4447f106e74ecf4d1404f080245f3e259703d58b09'),
        ),
    ]
