# Generated by Django 3.2.13 on 2022-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
    ]
