# Generated by Django 3.2.13 on 2022-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220525_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='imageBody',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='tittleBody',
            field=models.TextField(blank=True),
        ),
    ]
